### ISSUE TITLE
Crash on startup for KUbuntu 24.04

### ISSUE THREAD

**Issue by Mailaender** [Lin-Buo-Ren/git-cola-snap#15]
```
Traceback (most recent call last):
  File "/snap/git-cola/136/bin/git-cola", line 53, in <module>
    from cola.main import main
  File "/snap/git-cola/136/share/git-cola/lib/cola/main.py", line 6, in <module>
    from . import app
  File "/snap/git-cola/136/share/git-cola/lib/cola/app.py", line 26, in <module>
    from qtpy import QtGui
  File "/snap/git-cola/136/share/git-cola/lib/qtpy/QtGui.py", line 21, in <module>
    from PyQt5.QtGui import *
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /var/lib/snapd/lib/gl/libGLdispatch.so.0)
```

**Comment by nickstoughton** [comment]
Seeing the same thing on Ubuntu mainline.
